Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"
  config.vm.hostname = "ftp"
  config.vm.network "private_network", ip: "192.168.56.39"

   config.vm.provider "virtualbox" do |vb|
     vb.memory = "512"
     vb.name = "ftp"
     vb.cpus = 1
   end

end

